/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include <stdio.h>

/* The following function is executed in Thread Mode + Priv Access Level of the processor */
void generate_interrupt()
{
	// Thread mode is in an unpriviledged access level
	// The following instructions will not be executed
	// set pointer variable to the HEX addresses
	uint32_t *pSTIR	 = (uint32_t*)0XE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	// de-reference the pointer variable
	// enable IRQ3 interrupt - set bit #3 to 1
	*pISER0 |= (1 << 3);

	// generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF);
}

void change_access_level_unpriv(void)
{
	// in order to change the access level
	// the control register flag has to be modified
	// control

	// read
	__asm volatile("MRS R0,CONTROL ");
	// modify
	// ORR instruction used to set the 0th-bit
	__asm volatile("ORR R0,R0,#0x01");
	// write
	// change the access from un-privilege to privilege
	__asm volatile("MSR CONTROL, R0");

}

// Main function called after processor is Reset
// After Reset - Reset Handler is called first
// And, Reset Handler calls main()
int main(void)
{
	printf("In thread mode : before interrupt\n");

	// First Change the access level - and then generate the interrupt
	change_access_level_unpriv();
	generate_interrupt();
	printf("In thread mode : after interrupt\n");
	printf("arm_cortex_m4_dev\n");
	for(;;);
}

/* ISR executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHANDLER(void)
{
	printf("In handler mode : ISR\n");
}

void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}
